### ISSUE TITLE
Redis optimization to cache user location from MapPage for art sharing

### ISSUE THREAD

**Issue by meghailango** [scalableinternetservices/wanderlust#67]

**Comment by Timthetic** [comment]
I'm a bit uncertain about this one. Redis lives on the server, but the client uses the Geolocation API to get its location and provides this data to the server in a request (at least I think that's how it works). I'm having trouble connecting the dots on how Redis is able to help here. Am I misunderstanding something?

**Comment by meghailango** [comment]
agreed, on second thought don't think it would help since this is client-side
